# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'

target 'YLZG' do
    
    pod 'AFNetworking', '~> 3.1.0'
    pod 'Masonry', '~> 1.0.1'
    pod 'SDWebImage', '~> 3.8.1'
    pod 'MJExtension', '~> 3.0.10'
    pod 'MJRefresh'
    pod 'FMDB'
    pod 'IQKeyboardManager'
    pod 'BaiduMapKit'
    pod 'UMengAnalytics'
    
    pod 'Hyphenate_CN'#, '~> 3.2.2'
    pod 'pop'
    pod 'MWPhotoBrowser'
    pod 'YYKit'
    pod 'JPush-iOS-SDK'
    pod 'LCActionSheet'
    pod 'PDTSimpleCalendar', '~> 0.9.1'

  target 'YLZGTests' do
    inherit! :search_paths
  end

  target 'YLZGUITests' do
    inherit! :search_paths
  end

end
